### ISSUE TITLE
Type expected.  TS1110 in version 5.1.2

### ISSUE THREAD

**Issue by tonyabracadabra** [apache/echarts#15544]
### Version
5.1.2

### Steps to reproduce
Using bar chart

### What is expected?
no errors

### What is actually happening?
Type expected.  TS1110

    6389 |     $vars: string[];
    6390 | } & {
  > 6391 |     [key in `${ComponentMainType}Index`]: number;
         |             ^
    6392 | } & {
    6393 |     [key in string]: unknown;
    6394 | };

**Comment by plainheart** [comment]
Could you help confirm the version of ECharts again? We've fixed it in #14722 and released [v5.1.1](https://echarts.apache.org/en/changelog.html#v5-1-1).

Related issues:

- #14716
- #14739

**Comment by lishaoh** [comment]
@plainheart it is still happened in v5.2.0
https://github.com/apache/echarts/issues/15749
