### ISSUE TITLE
Graph tooltips do not show when all input values are null but all will show given at least one valid input

### ISSUE THREAD

**Issue by htr3n** [apache/echarts#15757]
### Version
5.2.0

### Reproduction link
[https://codepen.io/htr3n/pen/bGRvyJJ](https://codepen.io/htr3n/pen/bGRvyJJ)

### Steps to reproduce
1. Create a simple ECharts line graph example 
2. Configure ECharts option in which, tooltip is triggered and all input data are assigned to null
3. Pass the option to ECharts engine.

```
const options = {
  tooltip: {
    trigger: "axis",
    axisPointer: {
      type: "shadow",
      label: {
        show: true,
        overflow: "break"
      }
    }
  },
  xAxis: {
    type: "category",
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: [
    {
      type: "value",
    },
  ],
  series: [
    {
      type: "line",
      data: [null, null, null, null, null, null, null],
    }
  ]
};
```
 

### What is expected?
The tooltip should show off when it is configured to be triggered.

### What is actually happening?
No tooltip has been shown.

---
Step 4. Assign any value of the series input to a valid number, e.g. 1, then all tooltips will show, even the ones with the `null` values.

**Comment by htr3n** [comment]
This is the MWE with at least one non-null value: https://codepen.io/htr3n/pen/JjJLQYr. 

All tooltips are displayed properly with either `-` for `null` or the actual value.

**Comment by Ayushsunny** [comment]
Hey, @htr3n I think we have to put zero instead of null to show when all of the values are null(zero).

[see this](https://codepen.io/ayushsunny/pen/ExXrgMP)

```
const container = document.getElementById("main");
const chart = echarts.init(container);

const options = {
  tooltip: {
    trigger: "axis",
    axisPointer: {
      type: "shadow",
      label: {
        show: true,
        overflow: "break"
      }
    }
  },
  xAxis: {
    type: "category",
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: [
    {
      type: "value",
    },
  ],
  series: [
    {
      type: "line",
      data: [0, 0, 0, 0, 0, 0, 0],
    }
  ]
};

chart.setOption(options, true);
```

**Comment by htr3n** [comment]
@Ayushsunny thanks for that. I know the case of `0` but it's not valid for my use case because `0` is actually valid data and `null` is not valid data (for instance, the end-user does not enter anything for an optional field). If we use an array of `0` as your example, the graph will have a line connecting the zero points, which is not what we would want.

**Comment by htr3n** [comment]
@pissang Is the fix released? Which version is that? 
Thanks.

**Comment by pissang** [comment]
@htr3n It will be included in the 5.3.0 which will be released later this month.

**Comment by zhenhuiWang** [comment]
> @htr3n It will be included in the 5.3.0 which will be released later this month.

I had the same problem, my echarts version is 5.4.1, this problem still exists.
