### ISSUE TITLE
[Bug] package.json is missing a package "type": "module" description

### ISSUE THREAD

**Issue by AndreyYolkin** [apache/echarts#16709]
### Version

5.3.1

### Steps to Reproduce

Create app with nuxt bridge
Build that app using nuxi build
preview this app using nuxi preview

### Current Behavior

Node throws error while trying import package as cjs module

### Expected Behavior

Node import package as esm module

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome 97
- Framework: Nuxt 2 Bridge
```

### Any additional comments?

After building the application with nuxt bridge and running the application, Node tryes to import echarts and zrender as CJS modules, but there are ESM, as I can see. After I specified "type": "module" in both packages, the problem has been solved.

Please specify module type in package.json

**Comment by FibreFoX** [comment]
Having this only as ESM makes it unusable following the "minimal bundle" instructions when using CRA/using Jest.
https://github.com/facebook/create-react-app/issues/12063

It is impossible to run tests, but works fine while building or developing ... makes the "minimal bundle" with TypeScripts unusable.

**Comment by AndreyYolkin** [comment]
Bump, this feature is really important as Vite-based framework sometimes does not work with this format.
@100pah sorry for mentioning, but may you ship this at 5,5 or nearest milestones.
[https://github.com/sheremet-va/dual-packaging requires only ](https://github.com/sheremet-va/dual-packaging#rollupconfigjs) does not require a lot

**Comment by Sujith1799** [comment]
@FibreFoX any workaround or fixes to get jest working with minimal bundle?

**Comment by FibreFoX** [comment]
@Sujith1799 not yet, the only workaround I know is to not import the page when testing, as suggested here: https://github.com/facebook/create-react-app/issues/12063#issuecomment-1215725669

Something like this:
```js
    // important: exclude this from testing, because Jest is unable to work with Apache EChart
    //  https://github.com/facebook/create-react-app/issues/12063
    const YourComponentWithEcharts = (process.env.NODE_ENV === "test") ? (() => {
        return null;
    }) : lazy(() => import("./YourComponentWithEcharts"));
```

This does not "make it testable", it just makes jest jump over the problematic stuff (until its fixed).

**Comment by Sujith1799** [comment]
Cool Thanks for this.

**Comment by Jordi-LG** [comment]
Hi, any updates for the issue ? I'm also stuck and got this error when i tried to compil my app.

`import * as echarts from 'echarts'` with echarts 5.4.1

```
export * from './lib/export/charts.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
```

**Comment by Jelenkee** [comment]
similar issue here
in fact `import * as echarts from "echarts"` does work, but `import * as echarts from "echarts/core"` doesn't.
Error: `export * from './lib/export/core.js';`

**Comment by phlegx** [comment]
Same problem using Vite and echarts 5.4.2.

```log
export * from './lib/export/core.js';
^^^^^^

SyntaxError: Unexpected token 'export'
  ...
```

**Comment by NeoN0x** [comment]
Same issue for me.

Nuxt 3.8.2 & latest echarts.

**Comment by rock-eb** [comment]
Same problem for me.
next@12.3.4 and echarts@5.4.2

**Comment by 100pah** [comment]
Fixed by #19513

**Comment by homj** [comment]
@100pah this issue still occurs in jest when importing like this:

```ts
import { BarChart } from 'echarts/charts';
```

**Comment by wilkie** [comment]
Yes, when using the minimized entrypoints with something bundled, it doesn't seem to work. It's expecting common-js and it is getting a module. There would need to be a build of the package where each entrypoint has a common-js build and then the `package.json` would express this in the `exports` section as something like:

```
  "exports": {
    ...
    "./charts": {
      "import": "./dist/charts.js", // The normal build that already exists
      "require": "./dist/charts.cjs" // A new exposed build that is pre-transformed
    },
    ...
  }
```

I think.
