### ISSUE TITLE
[Bug] The yAxis configuration item nameTextStyle.width does not work。yAxis的name配置项TextStyle.width不起作用

### ISSUE THREAD

**Issue by l406054531** [apache/echarts#18408]
### Version

5.1.1

### Steps to Reproduce

 yAxis: [{
    type: "value",
    nameTextStyle: {
      fontStyle: "normal",
      width: 1,
      overflow: "break",
      color: "rgba(211, 28, 28, 1)",
      fontSize: 12
    },
    name: "哈哈哈哈哈"
  }],

### Current Behavior

I want to give the yAxis name a width

我给yAxis的TextStyle.width设置了1，但不起作用

### Expected Behavior

The width of yAxis can be set successfully

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by ptandler** [comment]
I just noticed this as well: the axis name does not wrap, seems like width / overflow are ignored.

My [sample code (see in editor)](https://echarts.apache.org/examples/en/editor.html?code=b3B0aW9ucyA9IG9wdGlvbiA9IHsKICBjb2xvcjogWyIjMzM5OERCIl0sCiAgdG9vbHRpcDogewogICAgdHJpZ2dlcjogImF4aXMiLAogICAgYXhpc1BvaW50ZXI6IHsKICAgICAgdHlwZTogInNoYWRvdyIKICAgIH0KICB9LAogIGdyaWQ6IHt9LAogIHhBeGlzOiBbewogICAgdHlwZTogImNhdGVnb3J5IiwKICAgIGRhdGE6IFsiTW9uIiwgIlR1ZSIsICJXZWQiLCAiVGh1IiwgIkZyaSIsICJTYXQiLCAiU3VuIl0KICB9XSwKICB5QXhpczogW3sKICAgIHR5cGU6ICJ2YWx1ZSIsCiAgICBuYW1lOidhYmMgZGVmIGdoaSBqa2wgbW5vcCcsCiAgICBuYW1lVGV4dFN0eWxlOiB7CiAgICAgIHdpZHRoOiA1MCwKICAgICAgb3ZlcmZsb3c6ICdicmVhaycKICAgIH0KICB9XSwKICBzZXJpZXM6IFt7CiAgICBuYW1lOiAiYWJjIGRlZiIsCiAgICB0eXBlOiAiYmFyIiwKICAgIGJhcldpZHRoOiAiNjAlIiwKICAgIGRhdGE6IFsxMCwgNTIsIDIwMCwgMzM0LCAzOTAsIDMzMCwgMjIwXQogIH1dCn0=&enc=base64):

```js
options = option = {
  color: ["#3398DB"],
  tooltip: {
    trigger: "axis",
    axisPointer: {
      type: "shadow"
    }
  },
  grid: {},
  xAxis: [{
    type: "category",
    data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
  }],
  yAxis: [{
    type: "value",
    name:'abc def ghi jkl mnop',
    nameTextStyle: {
      width: 50,
      overflow: 'break'
    }
  }],
  series: [{
    name: "abc def",
    type: "bar",
    barWidth: "60%",
    data: [10, 52, 200, 334, 390, 330, 220]
  }]
}
```

**Comment by helgasoft** [comment]
yes, [nameTextStyle](https://echarts.apache.org/en/option.html#yAxis.nameTextStyle) has problems.
Workaround is to use line-breaks in the name text, like ```name: 'abc def ghi \n jkl mnop'```

**Comment by jydeng** [comment]
I'm using 5.4.3, the option nameTextStyle.width still not working

**Comment by NacoHayashi** [comment]
5.4.3 still not working QQ

**Comment by Ovilia** [comment]
Fixed in https://github.com/apache/echarts-doc/commit/0d22eaa136bf6c06486ec9a8910f12f27306d69c

**Comment by ptandler** [comment]
> Fixed in [apache/echarts-doc@0d22eaa](https://github.com/apache/echarts-doc/commit/0d22eaa136bf6c06486ec9a8910f12f27306d69c)

I'm a bit puzzled now: When I look at https://github.com/apache/echarts-doc/commit/0d22eaa136bf6c06486ec9a8910f12f27306d69c this adds docs about `nameTruncate` and `maxWidth`. However, this issue here is not about missing documentation, but rather about bugs in eChart WRT setting the with and wrapping. Do I miss something?

I'd vote for re-opening this.

**Comment by mkf62** [comment]
This is still broken, or something related to this issue is. Using TypeScript, the overflow property does not exist in echarts.d.ts:

This code
```
let yAxisConfig: YAXisComponentOption[] = [
  {
	name: axisLabel1.join(' '),
	nameRotate: 90,
	nameLocation: 'middle',
	nameGap: 55,
	nameTextStyle: {
		backgroundColor: 'lightgreen',
		width: 50,
		overflow: 'break',
	},
	type: 'value',
	min: 'dataMin',
	max: 'dataMax',
  }
]
```

Produces this typescript error:
```
Object literal may only specify known properties, and 'overflow' does not exist in type 'AxisNameTextStyleOption'.ts(2353)
echarts.d.ts(2389, 5): The expected type comes from property 'nameTextStyle' which is declared here on type 'YAXisOption'
```

Relevant sections of `echarts.ds.ts`:
```
export (..., YAXisOption as YAXisComponentOption, ...}
```
```
interface AxisBaseOptionCommon extends ComponentOption, AnimationOptionMixin {
    //...
    nameTextStyle?: AxisNameTextStyleOption;
    //...
```
```    
interface AxisNameTextStyleOption extends TextCommonOption {
    rich?: Dictionary<TextCommonOption>;
}
```
```
interface TextCommonOption extends ShadowOptionMixin {
    color?: string;
    fontStyle?: ZRFontStyle;
    fontWeight?: ZRFontWeight;
    fontFamily?: string;
    fontSize?: number | string;
    align?: HorizontalAlign;
    verticalAlign?: VerticalAlign;
    baseline?: VerticalAlign;
    opacity?: number;
    lineHeight?: number;
    backgroundColor?: ColorString | {
        image: ImageLike | string;
    };
    borderColor?: string;
    borderWidth?: number;
    borderType?: ZRLineType;
    borderDashOffset?: number;
    borderRadius?: number | number[];
    padding?: number | number[];
    width?: number | string;
    height?: number;
    textBorderColor?: string;
    textBorderWidth?: number;
    textBorderType?: ZRLineType;
    textBorderDashOffset?: number;
    textShadowBlur?: number;
    textShadowColor?: string;
    textShadowOffsetX?: number;
    textShadowOffsetY?: number;
    tag?: string;
}
```

The `overflow` property is not present as the documentation describes.

**Comment by ehehaye** [comment]
Any updates yet?
