### ISSUE TITLE
[Bug] MarkArea not fully fixed in version 5.4.2

### ISSUE THREAD

**Issue by ily-salamat** [apache/echarts#18499]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/ily-salamat/pen/bGmVjGj

### Steps to Reproduce

I already opened this issue here #18130 and it's fixed in this PR #18229 and apparently it's not fully fixed because now there is a gap issue between bars and mark area

In 5.4.0 version works fine
See example: https://codepen.io/ily-salamat/pen/LYBZzNo

Now in 5.4.2  there is a gap issue
See example: https://codepen.io/ily-salamat/pen/bGmVjGj

### Current Behavior

Since version 5.4.2 there is a gap between bars and mark area

### Expected Behavior

MarkArea should works properly as in the previous version

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
@ily-salamat, just adding a [simplified update](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiWDh0bkAdADMOwALYAKMRPJKATAAYAjAHYAlFIDWVcniUGDJAL5905HPiJIylGrFoA3RgBsArlS8sHgAFsAA7kRgHIE8sAqMGEQ6WlqwdiR4VBwQVISwANr8xKSkFNR0AEaMHLwlgsJExWVlhQBsAKzxqVrxWgC69q3ohToAzH2wvT1DDaRjAJztPWnxGnMjoxrtUzOw45tbheMa3dNrsAAsRyMnizqrU523rYVXnSsXU-2vbZ0aDRPeJ6P4LHQQvTA2AADjBowhMMW0MW8KKOjOV2hqTRY3GOmR3x6OlxOiu2mxG2GdzJMPO-wmpM6nUeROmN2pbx07W52JenLa-k6e0u3NJMP02NBAvBMJhQLZOjhMoRiyuUMVqJVRW0ZOh2lx2gl-pJ2sKGjJGv2gIG8zBNQ4AHFGCAiH15gAvXxULxUXwpPjzB0AdQgAjAoQDsAA9NHUjKICwFABlCjelzzdD0YC-Th0DhUATBTOwUCMeiJ8huqSdeaZEZUBQgUKMPDOUpbRON1PkdMdrawbO5jh0ADEMhkVT0WnG9QH6DLFYoAZL6CqnAEOVD4cjsCBq9g644m44AGEc3nPOOqFQrlctLQSzY6zLEhxjGIqCJ-61G83W-2qDzrAXYpmmHhAcBg4XiOV5XDCTC3nOUGLpW1a1sBz4DvWWxej6fopO6A6gT2faQQOsaocusBaE-2pCGA34tPOzHAeRUHYLgBS0F0j5QRk2plOxwGce2tATA-B7oFh85oqMUk_iJTjcRJfFQThbEKegokqcsamYQeclFApwnzjpdAEu0-nzhp86mQO5meDskn8TJA5GaxdlaZgyl0M51nYYJpD2Vsjm0KcnQBVsblbB5JneWFEVRSMtkDiFIyJQ8yWtDFIxxfx6WtJlOjZWUqVbIVZRhR8VkKblrT5VBlWkNVnylaQ5UjM12m-Z4AIaO10mGUFnlpQlvW0P1g0CfF_E9VxFmQtN9VlI1mlzT5C2eBC-jLUF6DdZtYmIosy3DQeo0VeNW3iUqp11ftilmRNGKdFcZ3AWtXkbWFr3vQ9s1zb9-L3a553AZdXXXcdIN7YD_G_eSLnqeDLHwxxL1I3DBXQyp8GRXVqMDpDrSHYjdLY01uMWcyJWE59I3o0pN06LTlPrUDL08rVYMMxdTPPSz3Ps99nMs3owofbJjM4z9L0S8jmGPWTL0SnoUvuTLVNyyzasi2NOvHXKA309L_Oy2LRvyvrV2G7p6oa7FWscwjL1qurAMW67N26v9vNmxDAsORNvs21Ddt-VoEqO3lzui97YlGnTrnK9TTmWjHDUlraKUlDJRwMYwABawCKC4sBUNAAhEJMz42AA3CgKAQAgsDClojfZGAACS0AsBwPi-EolgIAAfMQCjkKeLYcGAUgCPgIDMPQoRYPQkAwEo7EVB4tCFyXijIegeCMbPABqfiBDX4zxJXAgXwEHgtzYBiN-gECIAAsswoRSIkGDDwgAAalSAYWAABSPcaRnhpFfigOwBxYH1yAA) of your demo.
Unwanted _markArea_ **overlaps** show as darker red stripes on auto-expanding zoom.

![image](https://user-images.githubusercontent.com/13038071/231858655-1b3ef36c-77da-47cb-a97f-3978a5368b57.png)

**Comment by ozkoidi** [comment]
It's been 3 months since the last comment. Any news on this? This is a regression (see #18130) and it should be fixed. The current status blocks us from using the latest versions

**Comment by plainheart** [comment]
@ozkoidi Apologies for this blocker. I've confirmed it is a bug that wasn't fixed by #18229 and will fix it soon.

**Comment by plainheart** [comment]
@ozkoidi After a simple dig, I think it's not a "bug" in this case. #17098 & #18229 (https://github.com/apache/echarts/pull/18229#discussion_r1126008965) make the `markArea` include the whole category, instead of starting from and ending at the center of the bar. It's the reason why the mark areas overlap. If the previous behavior is expected to be reserved, a new option (like `markOrigin`?) might be needed.

BTW, there seems to be another potential bug when the `axisTick.alignWithLabel` is set as `true`. See this [demo](https://echarts.apache.org/examples/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdPqViNceORHoBrIqnvoA9D9gAhAGwAO7aVHAABowANhCs0KoQYNoAMowARlQxkbD4sJFgHEqRPGThsAC2jBxuWBxUjLARAngOYAVmYLmWVBjU9CwCMeT8pLHxiclpmdlERUpjAL4kS3aw5Dj4nmMU1HQAbrFKtKvreFRGVISwomNe3kJgIrcAjACsAAxlAEwAzN9YD8fgAWX6vAAcZVef3e0JBAHZfgA2T62MboPY0WQZGq8DGwXEcJICFJEOEE6q1eqNHbeUhPF53en2Zks-wPdn2bBOOiKZQE-lrQXeTlc9A87ayQzGEX2Fbi6wipVC5YkJVLADcQA) for reproduction.

cc: @Ovilia @jiawulin001

**Comment by Chewieez** [comment]
I am also seeing the bug that @plainheart referred to at the end of his comment with `axisTick.alignWithLabel` in 5.4.3. 

I was able to work around it by attaching my markArea to a 2nd xAxis that has `axisTick.alignWithLabel = false`, while my first xAxis has it set to `true`.
